import { PREFIX_NAME } from "../../../const";

export const FORMATTED_SENSOR_CARD_NAME = `${PREFIX_NAME}-formatted-sensor-card`;
export const FORMATTED_SENSOR_CARD_EDITOR_NAME = `${FORMATTED_SENSOR_CARD_NAME}-editor`;

export const FORMATTED_SENSOR_CARD_DEFAULT_SHOW_NAME = true;
export const FORMATTED_SENSOR_CARD_DEFAULT_SHOW_STATE = true;
export const FORMATTED_SENSOR_CARD_DEFAULT_SHOW_ICON = true;
export const FORMATTED_SENSOR_CARD_DEFAULT_CLAMP_NEGATIVE = true;
